apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: 'example.com'
spec:
  secretName: sonar-test-ubeeqo-tls
  issuerRef:
    name: 'ubeeqotech'
    kind: ClusterIssuer
  commonName: 'example.com'
  dnsNames:
  - 'sonar-test.ubeeqo.tech'
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - 'example.com'
