apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: 'example.com'
spec:
  secretName: sonar-test-example.com-tls
  issuerRef:
    name: 'example.comtech'
    kind: ClusterIssuer
  commonName: 'example.com'
  dnsNames:
  - 'sonar-test.example.com.tech'
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
      - 'example.com'
