apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: example.comtech
spec:
 acme:
   server: https://acme-v02.api.letsencrypt.org/directory
   email: {{ .Values.letsencryptEmail }}
   privateKeySecretRef:
     name: {{ template "certificates.fullname" . }}-issuer
   dns01:
     providers:
       - name: {{ template "certificates.fullname" . }}-cf
         cloudflare:
           email: {{ .Values.cloudflareEmail }}
           apiKeySecretRef:
             name: {{ template "certificates.fullname" . }}-cloudflare
             key: {{ .Values.cloudflareApiKey }}